---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "konga.fullname" . }}
  labels:
    app: "{{ template "konga.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "konga.fullname" . }}
      component: ui
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "konga.name" . }}
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "konga.name" . }}
        image: '{{ .Values.konga.image.repository }}:{{ .Values.konga.image.tag }}'
        env:
        - name: DB_ADAPTER
          value: "postgres"
        - name: DB_DATABASE
          value: "postgres"
        - name: DB_HOST
          value: {{ template "konga.fullname" .  }}-postgres
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "konga.fullname" . }}-postgresql
              key: postgres-password
        - name: DB_USER
          value: {{ .Values.postgres.postgresUser }}
        - name: KONGA_BACKEND_PORT
          value: "8080"
        - name: NODE_ENV
          value: "development"
        ports:
        - name: kong-ui
          containerPort: 8080
