image:
  name: camptocamp/pghoard
  tag: 10.0

postgresql:
  # Name of the deployed postgresql chart
  name: postgres
  host:    # Defaults to postgresql.name
  secret:
    name:  # Defaults to postgresql.name
    key:   # Defaults to "postgres-password"
  port: 5432

backup:
  storage_type: local
  directory: /backup
  basebackup_count: 5

# Use nfs mount directly without pv / pvc
raw_nfs:
  enabled: false
  path: /
  server: nfs.local.dmz
  readonly: false

# Use claim for backups. `raw_nfs.enabled` should be false
volume_claim:
  enabled: false
  storageClassName: manual
  storageSize: 10Gi
