konga:
  image:
    repository: pantsel/konga
    tag: 0.14.1
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  class: ""
  domain: zoobab4ever.mycluster.com

postgres:
  postgresUser: konga
  postgresPassword: konga
  postgresDatabase: konga
  persistence:
    enabled: true
    storageClass: "-"
  metrics:
    enabled: false
