---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backup
  labels:
    app: {{ template "postgresql-backup.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "postgresql-backup.fullname" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "postgresql-backup.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}"
        env:
        - name: PGHOARD_STORAGE_TYPE
          value: {{ .Values.backup.storage_type | quote }}
        - name: PGHOARD_DIRECTORY
          value: {{ printf "%s/%s/%s" .Values.backup.directory .Release.Namespace .Release.Name | quote }}
        - name: PGHOARD_BASEBACKUP_COUNT
          value: {{ .Values.backup.basebackup_count | quote }}
        - name: PG_HOST
          value: {{ default .Values.postgresql.name .Values.postgresql.host | quote }}
        - name: PG_PORT
          value: {{ default "5432" .Values.postgresql.port | quote }}
        - name: PG_USER
          value: {{ default "postgres" .Values.postgresql.user | quote }}
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ default .Values.postgresql.name .Values.postgresql.secret.name }}
              key: {{ default "postgres-password" .Values.postgresql.secret.key }}
        volumeMounts:
        - name: {{ template "postgresql-backup.fullname" . }}-storage
          mountPath: {{ .Values.backup.directory }}
      restartPolicy: Always
      volumes:
      {{- if .Values.raw_nfs.enabled }}
      - name: {{ template "postgresql-backup.fullname" . }}-storage
        nfs:
          path: {{ .Values.raw_nfs.path }}
          server: {{ .Values.raw_nfs.server }}
          readOnly: {{ .Values.raw_nfs.readonly }}
      {{- else }}
      - name: {{ template "postgresql-backup.fullname" . }}-storage
      {{- if .Values.volume_claim.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "postgresql-backup.fullname" . }}-claim
      {{- else }}
        emptyDir: {}
      {{- end -}}
      {{- end -}}
