image:
  name: docker-reg.wild-beavers.de/mongodb-backup
  tag: "4.0"

mongodb:
  releasename:    # Name of the deployed mongodb chart
  host:    # Defaults to mongodb.name
  password:
  user:
  databasename:

backup:
  directory: "/backups"

raw_nfs:
  enabled: false
  path: /
  server: nfs.local.dmz
  readonly: false

# Use claim for backups. `raw_nfs.enabled` should be false
volume_claim:
  enabled: false
  storageClassName: manual
  storageSize: 1Gi
